apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unity-tls
  namespace: unity
spec:
  secretName: unity-tls-cert
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - ui.homelab.local
    - unity.homelab.local
    - "*.homelab.local"
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
