apiVersion: v1
kind: Secret
metadata:
  name: unity-secrets
  namespace: unity
type: Opaque
stringData:
  postgres-user: homelab_user
  postgres-password: WZJvFjSYAL-u-o3zQoi3QGoghz5i8WUJue3dxBeiyfA
  postgres-db: homelab_db
  redis-password: W7fjUROSIcI21JCYyByXKpHgGTeAq7_e50JNkRup0EE
  jwt-secret-key: 30DnECRBN5c9Doj0Rr82z3kqpevR0yk7fkqaSquQ3s-XeefMZowPuM9p-AezNFgWsrL5oCz5ephf2Y65-EKwfQ
  encryption-key: MGAuGlkwooIL45NDTNjn5n3HcSXKAgA_IpfLmsiqhPU=
---
apiVersion: v1
kind: Secret
metadata:
  name: unity-secrets
  namespace: holon
type: Opaque
stringData:
  postgres-user: holon_user
  postgres-password: WZJvFjSYAL-u-o3zQoi3QGoghz5i8WUJue3dxBeiyfA
  postgres-db: holon_db
  redis-password: W7fjUROSIcI21JCYyByXKpHgGTeAq7_e50JNkRup0EE
  jwt-secret-key: 30DnECRBN5c9Doj0Rr82z3kqpevR0yk7fkqaSquQ3s-XeefMZowPuM9p-AezNFgWsrL5oCz5ephf2Y65-EKwfQ
  encryption-key: MGAuGlkwooIL45NDTNjn5n3HcSXKAgA_IpfLmsiqhPU=
---
apiVersion: v1
kind: Secret
metadata:
  name: unity-secrets
  namespace: biz
type: Opaque
stringData:
  postgres-user: biz_user
  postgres-password: WZJvFjSYAL-u-o3zQoi3QGoghz5i8WUJue3dxBeiyfA
  postgres-db: biz_db
  redis-password: W7fjUROSIcI21JCYyByXKpHgGTeAq7_e50JNkRup0EE
  jwt-secret-key: 30DnECRBN5c9Doj0Rr82z3kqpevR0yk7fkqaSquQ3s-XeefMZowPuM9p-AezNFgWsrL5oCz5ephf2Y65-EKwfQ
  encryption-key: MGAuGlkwooIL45NDTNjn5n3HcSXKAgA_IpfLmsiqhPU=
